'use strict';
let tab='clinics', clinics=[], accounts=[];
window.addEventListener('DOMContentLoaded',boot);
async function boot(){await DCOS.Store.init();let ok=sessionStorage.getItem('dcos_v15_dashboard_ok')==='1';if(!ok){let p=prompt('أدخل كلمة سر Dental Chain Dashboard:');if(p!==ADMIN_PASS){document.body.innerHTML='<div class="center"><div class="card login"><h2>تم رفض الدخول</h2><p class="muted">كلمة السر غير صحيحة.</p><button onclick="location.reload()" class="primary">إعادة المحاولة</button></div></div>';return}sessionStorage.setItem('dcos_v15_dashboard_ok','1')}DCOS.$('app').classList.remove('hidden');await load();}
async function load(){clinics=await DCOS.getClinics();accounts=await DCOS.getAccountsAll();render();}
function roleName(r){return ({super_owner:'Super Owner',manager:'مدير عيادة',doctor:'طبيب',assistant:'مساعدة',reception:'الاستقبال'}[r]||r)}
function clinicLink(id){const c=clinics.find(x=>x.id===id)||{};return location.origin + location.pathname.replace(/dashboard\.html.*$/,'index.html') + '?clinic=' + encodeURIComponent(id) + '&clinicName=' + encodeURIComponent(c.name||'')}
function dcosCurrency(v){return String(v||'SYP').toUpperCase()==='USD'?'USD':'SYP'}
function dcosPatientFinance(p){
  const arr=v=>Array.isArray(v)?v:[];
  const n=v=>Math.abs(Number(v||0));
  const f=p?.finance||{};
  const uniq=rows=>{const seen=new Set();return arr(rows).filter(x=>{const k=String(x?.id||x?.paymentId||x?.chargeId||x?.financeChargeId||[x?.amount??x?.cost??x?.price,dcosCurrency(x?.currency),x?.isoDate||x?.date||x?.createdAt||'',x?.note||x?.label||x?.title||''].join('|'));if(seen.has(k))return false;seen.add(k);return true})};
  const rawCharges=uniq(arr(f.charges).length?f.charges:p?.charges);
  const charges=rawCharges.filter(x=>{const source=String(x?.source||x?.type||x?.kind||'').toLowerCase();const chartOnly=(source.includes('chart')||source.includes('dental'))&&!(x?.financialConfirmed===true||x?.billable===true||x?.completed===true||x?.status==='completed');return !chartOnly});
  const payments=uniq(arr(f.payments).length?f.payments:p?.payments);
  const out={SYP:{total:0,payments:0,paid:0,remain:0,credit:0},USD:{total:0,payments:0,paid:0,remain:0,credit:0}};
  charges.forEach(x=>out[dcosCurrency(x.currency)].total+=n(x.amount??x.cost??x.price));
  if(!charges.length){
    const fallback=n(p?.totalCost)||arr(p?.treatmentPlan||p?.plans).reduce((a,x)=>a+n(x.cost??x.price??x.amount),0);
    out.SYP.total+=fallback;
  }
  payments.forEach(x=>out[dcosCurrency(x.currency)].payments+=n(x.amount));
  Object.values(out).forEach(t=>{t.paid=Math.min(t.total,t.payments);t.remain=Math.max(t.total-t.payments,0);t.credit=Math.max(t.payments-t.total,0)});
  return out;
}
async function clinicStats(c){
  const patients=await DCOS.Store.list('clinics/'+c.id+'/patients');
  const out={patients:patients.length,paid:0,total:0,remain:0,credit:0,paidUSD:0,totalUSD:0,remainUSD:0,creditUSD:0,rx:0};
  patients.forEach(p=>{const f=dcosPatientFinance(p);out.paid+=f.SYP.paid;out.total+=f.SYP.total;out.remain+=f.SYP.remain;out.credit+=f.SYP.credit;out.paidUSD+=f.USD.paid;out.totalUSD+=f.USD.total;out.remainUSD+=f.USD.remain;out.creditUSD+=f.USD.credit;out.rx+=(p.prescriptions||[]).length});
  return out;
}
async function totalStats(){let out={patients:0,paid:0,total:0,remain:0,credit:0,paidUSD:0,totalUSD:0,remainUSD:0,creditUSD:0,rx:0};for(const c of clinics){let s=await clinicStats(c);Object.keys(out).forEach(k=>out[k]+=s[k])}return out}
async function render(){let s=await totalStats();let labDue={};try{labDue=await window.DCOS_LABS_DASHBOARD_TOTALS?.()||{}}catch(e){console.warn(e)}const labDueHtml=Object.entries(labDue).filter(([,v])=>Number(v)).map(([c,v])=>`<span>${String(c).toUpperCase()==='SYP'?Number(v).toLocaleString('en-US')+' ل.س':(c==='USD'?'$':c==='EUR'?'€':c)+' '+Number(v).toLocaleString('en-US')}</span>`).join('<br>')||'0 ل.س';DCOS.$('app').innerHTML=`<div class="dash-shell"><aside class="dash-side"><div class="dash-logo"><h2>Dental Chain</h2><p>لوحة إدارة الشبكة</p></div><div class="dash-menu card"><button class="${tab==='clinics'?'primary':''}" onclick="setTab('clinics')">🏥 العيادات</button><button class="${tab==='accounts'?'primary':''}" onclick="setTab('accounts')">👥 الحسابات</button><button class="${tab==='patients'?'primary':''}" onclick="setTab('patients')">🔎 سجل المرضى المركزي</button><button class="${tab==='audit'?'primary':''}" onclick="setTab('audit')">📜 سجل العمليات</button><button class="${tab==='labs'?'primary':''}" onclick="setTab('labs')">🧪 المخابر</button><button onclick="copyDash()">نسخ رابط الداشبورد</button></div></aside><main class="dash-main"><section class="hero"><div><h1>Dental Chain Dashboard</h1><p>واجهة مستقلة لإدارة الشبكة والعيادات والحسابات.</p></div><div class="badge">${clinics.length} عيادة · ${accounts.length} حساب</div></section><div class="stats-grid"><div class="kpi"><span class="icon">🏥</span><b>${clinics.length}</b><small>العيادات</small></div><div class="kpi"><span class="icon">👥</span><b>${s.patients}</b><small>المرضى</small></div><div class="kpi"><span class="icon">💵</span><b>${DCOS.money(s.paid)}</b><span class="dashboard-usd-line">$ ${s.paidUSD.toLocaleString('en-US')}</span><small>المقبوض الفعلي</small></div><div class="kpi"><span class="icon">💰</span><b>${DCOS.money(s.remain)}</b><span class="dashboard-usd-line">$ ${s.remainUSD.toLocaleString('en-US')}</span><small>الباقي</small></div><div class="kpi"><span class="icon">🧾</span><b>${DCOS.money(s.credit)}</b><span class="dashboard-usd-line">$ ${s.creditUSD.toLocaleString('en-US')}</span><small>رصيد المرضى لدى العيادة</small></div><button class="kpi" onclick="openAllLabDuesDashboard()"><span class="icon">🧪</span><b>${labDueHtml}</b><small>المستحق للمخابر</small></button></div><div id="panel"></div></main></div>`;renderPanel();}
window.setTab=function(t){tab=t;render();}
function renderPanel(){if(tab==='clinics')return renderClinics();if(tab==='accounts')return renderAccounts();if(tab==='patients')return renderPatients();if(tab==='audit')return renderAudit();if(tab==='labs')return window.renderLabsDashboard?.();}
async function renderClinics(){let cards=[];for(const c of clinics){let st=await clinicStats(c);cards.push(`<div class="patient-card"><div class="space"><h3>${c.name}</h3><span class="pill">${c.id}</span></div><p class="muted">${c.city||''} ${c.phone||''}</p><div class="grid"><div class="mini-card">المرضى<br><b>${st.patients}</b></div><div class="mini-card">المقبوض الفعلي<br><b>${DCOS.money(st.paid)}</b><span class="clinic-usd-line">$ ${st.paidUSD.toLocaleString('en-US')}</span></div><div class="mini-card">الباقي<br><b>${DCOS.money(st.remain)}</b><span class="clinic-usd-line">$ ${st.remainUSD.toLocaleString('en-US')}</span></div><div class="mini-card credit-mini-card"><span>رصيد المرضى</span><b>${DCOS.money(st.credit)}</b><span class="clinic-usd-line">$ ${st.creditUSD.toLocaleString('en-US')}</span><small>التزام مستقل على العيادة</small></div></div><br><input class="ltr" value="${clinicLink(c.id)}" readonly><br><br><div class="row"><button class="primary" onclick="copyClinic('${c.id}')">نسخ رابط العيادة</button><button onclick="editClinic('${c.id}')">تعديل</button><button onclick="clinicFinance('${c.id}')">مالية العيادة</button><button class="danger" onclick="deleteClinic('${c.id}')">حذف العيادة بالكامل</button></div></div>`)}
DCOS.$('panel').innerHTML=`<section class="card"><div class="space"><h2>العيادات المنفصلة</h2><button class="primary" onclick="newClinic()">إضافة عيادة</button></div><div class="grid">${cards.join('')||'<p>لا توجد عيادات</p>'}</div></section>`}
window.newClinic=function(){openDashModal(`<h2>إضافة عيادة</h2><div class="form-grid"><input id="cname" placeholder="اسم العيادة"><input id="ccity" placeholder="المدينة"><input id="cphone" placeholder="الهاتف"><input id="cid" placeholder="Clinic ID اختياري"></div><br><button class="primary" onclick="saveClinic()">حفظ</button><button onclick="closeDashModal()">إلغاء</button>`)}
window.editClinic=function(id){let c=clinics.find(x=>x.id===id);if(!c)return;openDashModal(`<h2>تعديل العيادة</h2><div class="form-grid"><input id="cname" value="${c.name||''}" placeholder="اسم العيادة"><input id="ccity" value="${c.city||''}" placeholder="المدينة"><input id="cphone" value="${c.phone||''}" placeholder="الهاتف"><input id="csubtitle" value="${c.subtitle||''}" placeholder="سطر تعريفي"></div><br><button class="primary" onclick="saveClinic('${c.id}')">حفظ</button><button onclick="closeDashModal()">إلغاء</button>`)}
window.saveClinic=async function(id=''){let c=id?clinics.find(x=>x.id===id):{};let newId=id||DCOS.safeId(DCOS.$('cid').value||('clinic_'+Date.now()));Object.assign(c,{id:newId,name:DCOS.$('cname').value||'عيادة جديدة',city:DCOS.$('ccity').value,phone:DCOS.$('cphone').value,subtitle:DCOS.$('csubtitle')?.value||c.subtitle||'',updatedAt:DCOS.now()});await DCOS.Store.set('network/clinics/'+newId,c);await DCOS.Audit.log(null,id?'edit_clinic':'create_clinic',c.name);closeDashModal();await load();}
window.deleteClinic=async function(id){let p=prompt('لحذف العيادة بالكامل اكتب كلمة السر:');if(p!==ADMIN_PASS)return alert('كلمة السر غير صحيحة');if(!confirm('سيتم حذف بيانات العيادة من المرضى والحسابات والسجل محليًا/سحابيًا قدر الإمكان. متابعة؟'))return;let cols=['patients','accounts','audit'];for(const col of cols){let rows=await DCOS.Store.list('clinics/'+id+'/'+col);for(const r of rows)await DCOS.Store.del('clinics/'+id+'/'+col+'/'+r.id)}await DCOS.Store.del('network/clinics/'+id);await DCOS.Audit.log(null,'delete_clinic',id);await load();}
window.copyClinic=function(id){navigator.clipboard?.writeText(clinicLink(id));DCOS.toast('تم نسخ رابط العيادة')}
window.copyDash=function(){navigator.clipboard?.writeText(location.origin+location.pathname+'?v=15.27');DCOS.toast('تم نسخ رابط الداشبورد')}
window.clinicFinance=async function(id){let s=await clinicStats(clinics.find(c=>c.id===id));alert(`مالية العيادة\nإجمالي التكلفة: ${DCOS.money(s.total)}\nالمقبوض الفعلي: ${DCOS.money(s.paid)}\nالباقي: ${DCOS.money(s.remain)}\nأرصدة زائدة للمرضى (التزام وليست دخلًا): ${DCOS.money(s.credit)}\n\nبالدولار:\nإجمالي التكلفة: $ ${s.totalUSD.toLocaleString('en-US')}\nالمقبوض الفعلي: $ ${s.paidUSD.toLocaleString('en-US')}\nالباقي: $ ${s.remainUSD.toLocaleString('en-US')}\nرصيد زائد: $ ${s.creditUSD.toLocaleString('en-US')}`)}
function renderAccounts(){let grouped=clinics.map(c=>({c,arr:accounts.filter(a=>a.clinicId===c.id)}));let superRows=accounts.filter(a=>a.role==='super_owner').map(accRow).join('');let html=`<section class="card"><div class="space"><h2>الحسابات</h2><button class="primary" onclick="newAccount()">إضافة حساب</button></div><h3>Super Owner</h3><table class="table"><thead><tr><th>الحساب</th><th>الدور</th><th>الحالة</th><th></th></tr></thead><tbody>${superRows||'<tr><td colspan="4">لا يوجد Super Owner بعد</td></tr>'}</tbody></table>`;grouped.forEach(g=>{html+=`<h3>${g.c.name} (${g.arr.length} حساب)</h3><table class="table"><thead><tr><th>الحساب</th><th>الدور</th><th>الحالة</th><th></th></tr></thead><tbody>${g.arr.map(accRow).join('')||'<tr><td colspan="4">لا توجد حسابات</td></tr>'}</tbody></table>`});html+='</section>';DCOS.$('panel').innerHTML=html}
function accRow(a){return `<tr><td><b>${a.name||a.email}</b><br><span class="muted">${a.email}</span><br><span class="muted">كلمة السر: ${a.password||'غير محفوظة'}</span></td><td>${roleName(a.role)}</td><td>${a.active===false?'موقوف':'فعال'}</td><td><button onclick="editAccount('${a.email}','${a.clinicId||''}')">تعديل</button> <button class="danger" onclick="removeAccount('${a.email}','${a.clinicId||''}')">حذف</button></td></tr>`}
window.newAccount=async function(){openDashModal(`<h2>إضافة حساب</h2><div class="form-grid"><input id="aemail" placeholder="البريد الإلكتروني"><input id="apass" placeholder="كلمة السر"><input id="aname" placeholder="الاسم"><select id="arole" onchange="document.getElementById('aclinicWrap').style.display=this.value==='super_owner'?'none':''"><option value="doctor">طبيب</option><option value="assistant">مساعدة</option><option value="reception">الاستقبال</option><option value="manager">مدير عيادة</option><option value="super_owner">Super Owner</option></select><div id="aclinicWrap"><select id="aclinic">${clinics.map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}</select></div></div><br><button class="primary" onclick="saveAccountDash()">حفظ</button><button onclick="closeDashModal()">إلغاء</button>`)}
window.saveAccountDash=async function(){let btn=event?.target;if(btn){btn.disabled=true;btn.textContent='جار الحفظ...'}try{let role=DCOS.$('arole').value;let acc={email:DCOS.$('aemail').value.trim().toLowerCase(),password:DCOS.$('apass').value,name:DCOS.$('aname').value,role,clinicId:role==='super_owner'?'':DCOS.$('aclinic').value,active:true};if(!acc.email||!acc.password){if(btn){btn.disabled=false;btn.textContent='حفظ'}return alert('أدخل البريد وكلمة السر')}await DCOS.saveAccount(acc);try{await DCOS.Audit.log(null,'save_account',acc.email)}catch(e){console.warn(e)}closeDashModal();await load();DCOS.toast('تم حفظ الحساب')}catch(e){console.error(e);alert('حدث خطأ أثناء الحفظ: '+(e.message||e));if(btn){btn.disabled=false;btn.textContent='حفظ'}}}
window.editAccount=async function(email,clinicId){let a=await DCOS.findAccount(email,clinicId);if(!a)return alert('لم أجد الحساب');let name=prompt('الاسم:',a.name||'')??a.name;let password=prompt('كلمة السر:',a.password||'')??a.password;let role=prompt('الدور:',a.role)??a.role;let active=confirm('OK = فعال / Cancel = موقوف');a={...a,name,password,role,active};if(role!=='super_owner')a.clinicId=prompt('Clinic ID:',a.clinicId||clinics[0]?.id||'')||a.clinicId;else a.clinicId='';await DCOS.saveAccount(a);await DCOS.Audit.log(null,'edit_account',email);await load();}
window.removeAccount=async function(email,clinicId){let a=await DCOS.findAccount(email,clinicId);if(!a)return;let p=prompt('اكتب كلمة السر لحذف الحساب:');if(p!==ADMIN_PASS)return alert('كلمة السر غير صحيحة');await DCOS.deleteAccount(a);await DCOS.Audit.log(null,'delete_account',email);await load();}
async function renderPatients(){
  let all=[];
  for(const c of clinics){let ps=await DCOS.Store.list('clinics/'+c.id+'/patients');ps.forEach(p=>all.push({...p,clinicName:c.name,clinicId:c.id}))}
  const rows=all.map(p=>{const f=dcosPatientFinance(p);return `<tr><td><b>${p.name||'بدون اسم'}</b><br><span class="muted">${p.fileNo||''} · ${p.phone||''}</span></td><td>${p.clinicName}</td><td>${DCOS.money(f.SYP.total)}<span class="dashboard-usd-line">$ ${f.USD.total.toLocaleString('en-US')}</span></td><td>${DCOS.money(f.SYP.paid)}<span class="dashboard-usd-line">$ ${f.USD.paid.toLocaleString('en-US')}</span></td><td>${DCOS.money(f.SYP.remain)}<span class="dashboard-usd-line">$ ${f.USD.remain.toLocaleString('en-US')}</span></td><td>${DCOS.money(f.SYP.credit)}<span class="dashboard-usd-line">$ ${f.USD.credit.toLocaleString('en-US')}</span>${(f.SYP.credit||f.USD.credit)?'<br><span class="muted">التزام للعيادة</span>':''}</td></tr>`}).join('');
  DCOS.$('panel').innerHTML=`<section class="card"><h2>سجل المرضى المركزي - عرض فقط</h2><p class="muted">المقبوض لا يتجاوز تكلفة العلاج. أي مبلغ زائد يظهر كرصيد مستقل لصالح المريض ولا يدخل في إيراد العيادة.</p><input id="psearch" placeholder="بحث..." oninput="filterPatients()"><table class="table"><thead><tr><th>المريض</th><th>العيادة</th><th>تكلفة العلاج</th><th>المقبوض الفعلي</th><th>الباقي</th><th>رصيد زائد</th></tr></thead><tbody id="ptbody">${rows}</tbody></table></section>`
}
window.filterPatients=function(){let q=DCOS.$('psearch').value.toLowerCase();document.querySelectorAll('#ptbody tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?'':'none')}
async function renderAudit(){let rows=await DCOS.Store.list('network/audit');for(const c of clinics){let a=await DCOS.Store.list('clinics/'+c.id+'/audit');rows.push(...a.map(x=>({...x,clinicName:c.name})))}rows.sort((a,b)=>String(b.at).localeCompare(String(a.at)));DCOS.$('panel').innerHTML=`<section class="card"><h2>سجل العمليات</h2><table class="table"><thead><tr><th>الوقت</th><th>العملية</th><th>المستخدم</th><th>التفاصيل</th></tr></thead><tbody>${rows.slice(0,160).map(r=>`<tr><td>${r.at||''}</td><td>${r.action||''}</td><td>${r.user||''}</td><td>${r.details||r.clinicName||''}</td></tr>`).join('')}</tbody></table></section>`}
function openDashModal(html){let root=document.getElementById('modalRoot');if(!root){root=document.createElement('div');root.id='modalRoot';document.body.appendChild(root)}root.innerHTML=`<div class="modal-back"><div class="modal">${html}</div></div>`}
window.closeDashModal=function(){let r=document.getElementById('modalRoot');if(r)r.innerHTML=''}
